services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: hrt_postgres
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hrt-network

  redis:
    image: redis:alpine
    container_name: hrt_redis
    restart: no
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - hrt-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: hrt_elasticsearch
    restart: no
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - hrt-network
  neo4j:
    image: neo4j:5.19
    container_name: hrt_neo4j
    restart: no
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "${NEO4J_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - hrt-network

  ai_service:
    build: 
      context: ./BE/ai-service
      dockerfile: Dockerfile
    container_name: hrt_ai_service
    restart: no
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    networks:
      - hrt-network

  ollama:
    image: ollama/ollama:latest
    container_name: hrt_ollama
    restart: no
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - hrt-network

  ollama-init:
    image: ollama/ollama:latest
    container_name: hrt_ollama_init
    depends_on:
      - ollama
    networks:
      - hrt-network
    entrypoint: ["sh", "-c", "sleep 10 && OLLAMA_HOST=ollama:11434 ollama pull qwen3-embedding:0.6b"]

  backend:
    image: myapah/hr-tech-web-application-backend:latest
    build:
      context: ./BE/HrTech
      dockerfile: Dockerfile
    container_name: hrt_backend
    restart: no
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      neo4j:
        condition: service_started
    networks:
      - hrt-network
volumes:
  postgres_data:
  redis_data:
  neo4j_data:
  ollama_data:
  elastic_data:
networks:
  hrt-network:
