export const capitalizeSkill = (str: string): string => {
  if (!str) return ''
  const specialCases: Record<string, string> = {
    react: 'React',
    javascript: 'JavaScript',
    typescript: 'TypeScript',
    html: 'HTML',
    css: 'CSS',
    springboot: 'Spring Boot',
    mysql: 'MySQL',
    restapi: 'REST API',
    nodejs: 'Node.js',
    mongodb: 'MongoDB',
    express: 'Express',
    flutter: 'Flutter',
    dart: 'Dart',
    firebase: 'Firebase',
    ios: 'iOS',
    android: 'Android',
    docker: 'Docker',
    kubernetes: 'Kubernetes',
    aws: 'AWS',
    cicd: 'CI/CD',
    python: 'Python',
    sql: 'SQL',
    tableau: 'Tableau',
    excel: 'Excel',
    selenium: 'Selenium',
    cypress: 'Cypress',
    testing: 'Testing',
    automation: 'Automation',
    figma: 'Figma',
    sketch: 'Sketch',
    adobexd: 'Adobe XD',
    design: 'Design',
    linux: 'Linux',
    networking: 'Networking',
    bash: 'Bash',
    windowsserver: 'Windows Server',
    tensorflow: 'TensorFlow',
    pytorch: 'PyTorch',
    machinelearning: 'Machine Learning',
    swift: 'Swift',
    objectivec: 'Objective-C',
    xcode: 'Xcode',
    kotlin: 'Kotlin',
    golang: 'Golang',
    postgresql: 'PostgreSQL',
    redis: 'Redis',
    microservices: 'Microservices',
    vuejs: 'Vue.js',
    tailwind: 'Tailwind',
    azure: 'Azure',
    architecture: 'Architecture',
    systemdesign: 'System Design',
    scikitlearn: 'Scikit-Learn',
    keras: 'Keras',
    datascience: 'Data Science',
    oracle: 'Oracle',
    sqlserver: 'SQL Server',
    performancetuning: 'Performance Tuning',
    cybersecurity: 'Cybersecurity',
    penetrationtesting: 'Penetration Testing',
    owasp: 'OWASP',
    agile: 'Agile',
    scrum: 'Scrum',
    leadership: 'Leadership',
    productstrategy: 'Product Strategy',
    r: 'R',
    statistics: 'Statistics',
    datamining: 'Data Mining',
  }
  const key = str.toLowerCase()
  if (specialCases[key]) return specialCases[key]
  return str.charAt(0).toUpperCase() + str.slice(1)
}
