export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  SCORED = 'SCORED',
  CV_REJECTED = 'CV_REJECTED',
  INTERVIEW = 'INTERVIEW',
  FINAL_ACCEPTED = 'FINAL_ACCEPTED',
  FINAL_REJECTED = 'FINAL_REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}
