export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  SCORED = 'SCORED',
  PENDING_INTERVIEW_SCHEDULE = 'PENDING_INTERVIEW_SCHEDULE',
  CANDIDATE_REQUESTED_INTERVIEW_RESCHEDULE = 'CANDIDATE_REQUESTED_INTERVIEW_RESCHEDULE',
  INTERVIEW = 'INTERVIEW',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}
