export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  SCORED = 'SCORED',
  PENDING_INTERVIEW_SCHEDULE = 'PENDING_INTERVIEW_SCHEDULE',
  CANDIDATE_REQUESTED_INTERVIEW_RESCHEDULE = 'CANDIDATE_REQUESTED_INTERVIEW_RESCHEDULE',
  INTERVIEW = 'INTERVIEW',
  INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED',
  NO_SHOW = 'NO_SHOW',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}
