export enum NotificationType {
  APPLICATION_STATUS_UPDATED = 'APPLICATION_STATUS_UPDATED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  NEW_JOB_POSTED = 'NEW_JOB_POSTED',
  SUBSCRIPTION_UPGRADED = 'SUBSCRIPTION_UPGRADED',
  JOB_STATUS_UPDATED = 'JOB_STATUS_UPDATED',
}
