spring.application.name=HrTech

# =========================
# DATABASE (POSTGRESQL)
# =========================
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# =========================
# REDIS
# =========================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.password=

jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
jwt.refresh-expiration=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
jwt.issuer=${JWT_ISSUER}
jwt.audience=${JWT_AUDIENCE}

# =========================
# SMTP (MAIL)
# =========================
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}

spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.from=${SMTP_FROM_EMAIL}

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG
# =========================
# DATABASE (NEO4J)
# =========================
spring.neo4j.uri=bolt://${NEO4J_HOST}:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=12345678

# =========================
# SEED DATA
# =========================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# =========================
# MULTIPART (FILE UPLOAD)
# =========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# =========================
# CLOUDINARY
# =========================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# =========================
# AI SERVICE (PYTHON FASTAPI)
# =========================
ai.service.url=${AI_SERVICE_URL}

# =========================
# RECOMMENDATION SCORING
# =========================
recommendation.graph-weight=${RECOMMENDATION_GRAPH_WEIGHT}
recommendation.embedding-weight=${RECOMMENDATION_EMBEDDING_WEIGHT}
