spring.application.name=HrTech

# =========================
# DATABASE (POSTGRESQL)
# =========================
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}${POSTGRES_SSL_OPTION:}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# HikariCP Connection Pool Configuration
spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# =========================
# REDIS
# =========================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.password=
# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
jwt.refresh-expiration=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
jwt.issuer=${JWT_ISSUER}
jwt.audience=${JWT_AUDIENCE}
# =========================
# SMTP (MAIL)
# =========================
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.from=${SMTP_FROM_EMAIL}

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG
# =========================
# DATABASE (NEO4J)
# =========================
spring.neo4j.uri=${NEO4J_URL}
spring.neo4j.authentication.username=${NEO4J_USER}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}
# =========================
# SEED DATA
# =========================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=\
classpath:sql/01_roles.sql,\
classpath:sql/02_users.sql,\
classpath:sql/03_subscription_plans.sql,\
classpath:sql/04_companies.sql,\
classpath:sql/06_role_aliases.sql
# =========================
# MULTIPART (FILE UPLOAD)
# =========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# =========================
# CLOUDINARY
# =========================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
# =========================
# AI SERVICE (PYTHON FASTAPI)
# =========================
ai.service.url=${AI_SERVICE_URL}
# =========================
# APPLICATION LINKS
# =========================
app.frontend-base-url=${APP_FRONTEND_BASE_URL:http://localhost:3000}
# =========================
# PAYOS API
# =========================
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}