from .extraction import EXTRACTION_PROMPT, JOB_EXTRACTION_PROMPT
from .taxonomy import MAP_RELATIONSHIPS_PROMPT, VALIDATE_SKILLS_PROMPT
from .interview import INTERVIEW_QUESTIONS_PROMPT, EVALUATE_AUDIO_ANSWER_PROMPT, INTERVIEW_EVALUATION_PROMPT
from .matching import AI_MATCHING_ADVICE_PROMPT
from .job_review import JOB_REVIEW_PROMPT

__all__ = [
    "EXTRACTION_PROMPT",
    "JOB_EXTRACTION_PROMPT",
    "MAP_RELATIONSHIPS_PROMPT",
    "VALIDATE_SKILLS_PROMPT",
    "INTERVIEW_QUESTIONS_PROMPT",
    "EVALUATE_AUDIO_ANSWER_PROMPT",
    "INTERVIEW_EVALUATION_PROMPT",
    "AI_MATCHING_ADVICE_PROMPT",
    "JOB_REVIEW_PROMPT",
]
